sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5tapKX44eaAkq42YZV
    access-key-secret: Q9uEeuUp6ankTr4FwEgOFYQtkNC081
    bucket-name: reggie-itcast
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 5
  wechat:
    appid: wxffb3637a228223b8
    secret: 84311df9199ecacdf4f12d27b6b9522d
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\\pay\\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\\pay\\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://44b171fb.cpolar.io/notify/paySuccess
    refundNotifyUrl: https://44b171fb.cpolar.io/notify/refundSuccess
